### ISSUE TITLE
Problem with pairing.

### ISSUE THREAD

**Issue by Cukrovka** [TebbeUbben/SightRemote#12]
I have Xiaomi A1 with Oreo, latest version of Sightremote, and this problem with pairing. 

![36342049_1052763188214439_6821211431090782208_n](https://user-images.githubusercontent.com/23284874/42062128-e9400f4e-7b2c-11e8-9ade-48b20d090193.jpg)

**Comment by TebbeUbben** [comment]
Do you still need help?
