### ISSUE TITLE
Bluetooth Connection very unstable

### ISSUE THREAD

**Issue by fra-orolo** [TebbeUbben/SightRemote#14]
First: Great work, very clean code -- nice to read!

I tried SightRemote on a Samsung Phone with Android 6.0.1.
The pairing took 3-4 attempts to get it working. In the other cases it showed some hashmarks as error.
Directly after pairing it also downloads the history of pump-events which seems fine.
But if the app is opened again, it does not get any new connection to the pump. I tries to connect and one can also press the 'Connect now' button, but nothing happens.

It would be great to know, on which system the app actually worked. I would try to investigate the problem by debugging, but it would be great to have a positive example to compare with.
(E.G. borrow some other phone to run the app with proper connection.

**Comment by TebbeUbben** [comment]
Actually, establishing a Bluetooth connection can take a few attempts sometimes. Three to four attempts upon pairing is pretty much within range.

**Comment by fra-orolo** [comment]
> Actually, establishing a Bluetooth connection can take a few attempts sometimes. Three to four attempts upon pairing is pretty much within range.

Ok. I can accept that, although it seems to work better with other devices on the same phone.
But the main problem remains: after the initial connect bluetoothing with the pump  does not work **at all**.
All views that want to display information from the (paired) pump try to establish a connection and never get one (on my phone).

My question remains: on which hardware/android version is the app tested to work?

**Comment by TebbeUbben** [comment]
It works well on both of my devices: Asus Zenfone 3 and Google Pixel 2. You might ask other people on Gitter about what devices they use

**Comment by fra-orolo** [comment]
@DigitalDan1 : this is the same behavior as with the "Diabetes Mgr.", direct interaction with the pump takes priority and the remote gets active only, after the pump buttons are left alone.
This is clear to me. 
If found some dusty but functional Galaxy 2plus phone in a drawer, which can execute SightRemote successfully.

**Comment by TebbeUbben** [comment]
@fra-orolo It seems like your issue has been solved. Can I close this thread?
